# Google Gemini API 설정
# ----------------------
# 1. https://makersuite.google.com/app/apikey에서 API 키를 발급받으세요.
# 2. 발급받은 API 키를 아래 따옴표 안에 붙여넣으세요.
# 3. 이 파일은 .gitignore에 포함시켜 Git에 커밋되지 않도록 하세요.
# 4. Streamlit Cloud에 배포할 때는 웹 대시보드의 Secrets 섹션에 이 내용을 붙여넣으세요.

GEMINI_API_KEY = "AIzaSyAM_Qcq0CDj-NzRZcWVFoZKrdCzz9aCeas"
